"""add terms consent columns to users

Revision ID: 1735adbf9a12
Revises: 8409c18e07b1
Create Date: 2026-07-29 14:00:16.699548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1735adbf9a12'
down_revision: Union[str, None] = '8409c18e07b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tos_agreed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('tos_version', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('tos_agreed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('privacy_agreed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('privacy_version', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('privacy_agreed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('marketing_agreed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('marketing_version', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('marketing_agreed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_agreed_at')
    op.drop_column('users', 'marketing_version')
    op.drop_column('users', 'marketing_agreed')
    op.drop_column('users', 'privacy_agreed_at')
    op.drop_column('users', 'privacy_version')
    op.drop_column('users', 'privacy_agreed')
    op.drop_column('users', 'tos_agreed_at')
    op.drop_column('users', 'tos_version')
    op.drop_column('users', 'tos_agreed')
    # ### end Alembic commands ###
