"""add photo_url, coupons_count, push_enabled to users

Revision ID: 8409c18e07b1
Revises: 11f1df8450bf
Create Date: 2026-07-21 16:23:17.541185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8409c18e07b1'
down_revision: Union[str, None] = '11f1df8450bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('coupons_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('push_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_enabled')
    op.drop_column('users', 'coupons_count')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
