// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuqQQ4_vcF-k-9P8u7RzGoH1piJB4by4',
    appId: '1:260964288314:android:e402d80755b701a227f203',
    messagingSenderId: '260964288314',
    projectId: 'routour-5f540',
    storageBucket: 'routour-5f540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0fQAtxrYIWex4hjM-vif-DfELlD5uJg',
    appId: '1:260964288314:ios:3aa3501dac128dc027f203',
    messagingSenderId: '260964288314',
    projectId: 'routour-5f540',
    storageBucket: 'routour-5f540.firebasestorage.app',
    androidClientId: '260964288314-qf0sr9s0s9ebcc7eps80guvbdtijbfmj.apps.googleusercontent.com',
    iosClientId: '260964288314-epba0rr7neclvh7susrjuc4lo5cp6ahu.apps.googleusercontent.com',
    iosBundleId: 'com.routour.routour',
  );
}
